
/*
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
SOLUTION: 4613732
*/

public class Main
{
    private static final int MAX_VAL = 4000000;
    public static void main(String[] args)
    {
        System.out.println("FINAL: " + fib(1,2));
    }

    public static int fib(int i1, int i2)
    {

        if(i2 > MAX_VAL)
        {
            if(i1%2==0)
            {
                return i1;
            }
            return 0;
        }
        int k = fib(i2, i1+i2);
        //System.out.println(k);
        if(i1%2==0)
        {
            return i1+k;
        }
        return k;
    }
}
